### PR TITLE
Page now generating and reading url hash

### PR DESCRIPTION
**Pull request by chakler**
Latin 1, Latin 2, Cyrillic and Devenagari page is now reading and writing URL hash.

Every time you click on the tab menu, the browser will write the corresponding hash to the back of the URL with HTML5 History API. Then when the page is loaded, it will check if there's a hash attached to the URL hence decide wether to load a specific page or not.

So let's say you were at the Latin 1 – adhesion tab now and you want to go back to the immediate page in the future, all you need to do is to bookmark the page and open it next time.

### CODE REVIEW

**Comment by impallari** [comment]
I Love this, Thanks Thanks Thanks!

**Comment by davelab6** [comment]
Great to see Crafting Type's effects :D Thanks Aceler!

**Comment by chakler** [comment]
No problem! Glad I could help.

**Comment by impallari** [comment]
The browser's "Back" button does not work as expected. It only changes the URL hash but not the content of the tab. Any idea if this can be fixed?

**Comment by impallari** [comment]
For now I will remove the URL hash until the Back button is fixed (its a bit confusing, and break expectations), but will keep the init.js file.

**Comment by chakler** [comment]
It wasn't intended to be able to use for navigation with the browser's back and forward button since there are limitations in the History API for detecting popState in between pages.

But I admit it is my problem too for using pushState(Adding record to the history) instead of replaceState(Replacing the current record), it does create some confusions for the user. I'll make a new pull request for this.

**Pull request merged**
