### PR TITLE
fixed a typo in Tamil

### PR DESCRIPTION
**Pull request by enathu**
not நெருங்கணக்கு it's நெடுங்கணக்கு. Cheers. :)

### CODE REVIEW

**Comment by impallari** [comment]
We currently don't have a Tamil version, but will be adding one soon.
Will close this pull request temporarily until we add add it.

**Comment by davelab6** [comment]
But isn't this fixing an issue in the existing world scripts page?

**Comment by enathu** [comment]
@impallari As @davelab6 said, this pull request is for the existing world script page, which corrects a typo in Tamil paragraph.

**Comment by impallari** [comment]
Thanks Tharique Azeez!
I fixed the typo in the World Scripts tab, and also integrated your Tamil version into the main Testing page. Check it out.

**Comment by enathu** [comment]
That's great, Pablo. :+1:  Thank you for integrating my fork to main Testing page.

**Pull request closed without merging**
