### PR TITLE
Add Malayalam samples

### PR DESCRIPTION
**Pull request by santhoshtr**
Added Malayalam samples.

screenshot2

I have more test cases and I will add it later in another pull request :)

### CODE REVIEW

**Comment by impallari** [comment]
There is a small conflict with the recently added Hebrew.
If you can fix it, let me know (I don't know yet how to solve conflicts in github). Otherwise I can merge manually.

**Comment by impallari** [comment]
BTW, Thanks for adding Malayalam!!!

**Comment by santhoshtr** [comment]
> If you can fix it, let me know..

Fixed it. :)

**Comment by santhoshtr** [comment]
@impallari  ping :)

**Comment by davelab6** [comment]
@impallari ping :)

**Comment by davelab6** [comment]
@impallari ping

**Pull request merged**
